# Generated by Django 3.0.7 on 2020-07-11 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0002_auto_20200709_0151'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tweet',
            options={'ordering': ['-updated'], 'verbose_name_plural': 'Tweets'},
        ),
    ]
