# Generated by Django 3.0.7 on 2020-07-13 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0007_tweet_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='is_liked',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
